### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by ItaloCobains** [Morilli/bnk-extract-GUI#1]
Could make a readme, more interactive and instructional for contributors and users.

Add me on discord, I would like to discuss other matters with you
italowCobains#5180

**Comment by Morilli** [comment]
pushed fca922eff5ae07352178d39993503e8dc23ec111, does that look good?

**Comment by ItaloCobains** [comment]
It is already much better, from contributing to this readme, I will probably release a PR in the future leaving it with the most pleasant stretches
