### ISSUE TITLE
Is there a way to extract the Tree Folder structure with all the file names without a .bin file?

### ISSUE THREAD

**Issue by PaccianiMostro** [Morilli/bnk-extract-GUI#11]
Hey!
this is not really an issue but I didnt' see any other ways to contact you, once this is solved I can happily delete if it's a problem don't worry. I have these files here 
![image](https://github.com/user-attachments/assets/cbd5257e-5935-405e-a9e1-eebfa89f221e)
and I selected the .pck and .bnk files but they didn't work. I was wondering if you know a way to extract all the .ogg files and file names as well. 
Tysm!

**Comment by Morilli** [comment]
I assume the `*.pck` files are archive files containing multiple others. You'd need to find a way to extract those for the specific game in question and look for bnk files.

But keep in mind this tool is mainly made for league of legends, so I can't guarantee those files will parse or be modifiable by my program.

**Comment by PaccianiMostro** [comment]
I'm trying to extract sounds from Legends of Runeterra. Tbh I already extracted all the .ogg and .wem files, but the file names of these are just random numbers (probable the ID numbers of Wwise encryption). I was just trying to find a way to find the actual names of the assets (something like sfx_Card_Play_Whoosh.ogg or something) and match them with the .wem files. Any ideas?

**Comment by Morilli** [comment]
You can try with <https://github.com/Morilli/lor-vo-extractor>, although you'll need to build it yourself. I also can't guarantee anything about its functionality, but it does seem to get some useful names.

**Comment by PaccianiMostro** [comment]
Sadly it's outdated, I already contacted the dev. I now tried to use [wwiser](https://github.com/bnnm/wwiser-utils?tab=readme-ov-file), the only problem is that I haven't quite understood how to make it work, because I have all the .bnk and the .wem files but I'm missing the part on how to first find the original names of these files. Do you have any ideas?
