### ISSUE TITLE
can't get .bnk files

### ISSUE THREAD

**Issue by kaizawat** [Morilli/bnk-extract-GUI#3]
i modified some gragas voicelines, i can save .wpk files but can't save .bnk files.

**Comment by Morilli** [comment]
What happens when you try?

**Comment by kaizawat** [comment]
i only get wpk files. when i make a folder with saved .wpk file and original .bnk files and use it on cslol-manager to make a wad.client file, it only has .wpk file on it.

**Comment by Morilli** [comment]
If this is just a problem with the cslol-manager then you're probably just not creating the mod correctly, like using wrong filenames.

Saving .bnk files works fine for me, but if it doesn't for you, could you give me some reproduction steps?
