### ISSUE TITLE
.wem file names not ordered by event name?

### ISSUE THREAD

**Issue by MLXProjects** [Morilli/bnk-extract-GUI#5]
After opening skin0.bin, base_vo_audio.wpk and base_vo_events.bnk and parsing the files, all sounds are shown as their number/ID names instead of being separated into events.
Here is how it should look like:
![image](https://user-images.githubusercontent.com/40145907/226687749-1c9cd7fe-28c2-4760-8a7d-46a7271e8667.png)
and here is how it looks to me:
![image](https://user-images.githubusercontent.com/40145907/226687704-5fd0ecd0-f5ba-468c-94b6-adcc3200fc62.png)
Any advice/am I doing something wrong? Sound files were taken from <champion>_<locale>.wad.client (e.g. localised champion data) and skin0.bin comes from <champion>.wad.client (e.g. the base champion data)

**Comment by MLXProjects** [comment]
Sorry, I was doing things wrong :)
Needed to select correct skin0.bin (<champion>.wad.client/data/characters/<champion>/skins/skin0.bin), after that it loaded event names just fine.
I'll leave this here in case anybody faces the same issue.
![imagen](https://user-images.githubusercontent.com/40145907/226692336-3d4ef90f-2093-446a-9da1-1f74ac28e6bc.png)

**Comment by Morilli** [comment]
Which champion/skin does that happen with? Also, do you recall whether that specific combination has ever worked in the past?

The most likely explanation is that the bin file contains no event names, which does happen in very rare cases.

**Comment by MLXProjects** [comment]
> Which champion/skin does that happen with? Also, do you recall whether that specific combination has ever worked in the past?
> 
> The most likely explanation is that the bin file contains no event names, which does happen in very rare cases.

dont worry it was an error on my side, I was opening wrong bin :P sorry for wasting your time
btw are there big differences between this GUI app and the base bnk-extract in compat terms? seeing it's further updated than this

**Comment by Morilli** [comment]
> btw are there big differences between this GUI app and the base bnk-extract in compat terms? seeing it's further updated than this

I've done some commits but there should be no relevant differences in terms of behavior.
