### ISSUE TITLE
does the delete system32 button actually work

### ISSUE THREAD

**Issue by sami-25** [Morilli/bnk-extract-GUI#7]
I am deathly curious, i have to press it, but i know i shouldnt

**Comment by Morilli** [comment]
This here is all it does:
https://github.com/Morilli/bnk-extract-GUI/blob/7ec4555422312c20cdafda9689a9cadd4d455784/gui.c#L303-L308
https://github.com/Morilli/bnk-extract-GUI/blob/7ec4555422312c20cdafda9689a9cadd4d455784/utility.c#L385-L396
